export const countryList = [
  {
    srNo: 13,
    countryCode: 297,
    countryName: "Aruba",
    maxLength: 7,
  },
  {
    srNo: 1,
    countryCode: 93,
    countryName: "Afghanistan",
    maxLength: 9,
  },
  {
    srNo: 7,
    countryCode: 244,
    countryName: "Angola",
    maxLength: 9,
  },
  {
    srNo: 8,
    countryCode: 264,
    countryName: "Anguilla",
    maxLength: 10,
  },
  {
    srNo: 2,
    countryCode: 358,
    countryName: "Aland Islands",
    maxLength: 12,
  },
  {
    srNo: 3,
    countryCode: 355,
    countryName: "Albania",
    maxLength: 9,
  },
  {
    srNo: 6,
    countryCode: 376,
    countryName: "Andorra",
    maxLength: 6,
  },
  {
    srNo: 154,
    countryCode: 599,
    countryName: "Netherlands Antilles",
    maxLength: 7,
  },
  {
    srNo: 232,
    countryCode: 971,
    countryName: "United Arab Emirates",
    maxLength: 9,
  },
  {
    srNo: 11,
    countryCode: 54,
    countryName: "Argentina",
    maxLength: 10,
  },
  {
    srNo: 12,
    countryCode: 374,
    countryName: "Armenia",
    maxLength: 8,
  },
  {
    srNo: 5,
    countryCode: 684,
    countryName: "American Samoa",
    maxLength: 7,
  },
  {
    srNo: 9,
    countryCode: 672,
    countryName: "Antarctica",
    maxLength: 6,
  },
  {
    srNo: 77,
    countryCode: 0,
    countryName: "French Southern Territories",
  },
  {
    srNo: 10,
    countryCode: 268,
    countryName: "Antigua and Barbuda",
    maxLength: 10,
  },
  {
    srNo: 14,
    countryCode: 61,
    countryName: "Australia",
    maxLength: 9,
  },
  {
    srNo: 15,
    countryCode: 43,
    countryName: "Austria",
    maxLength: 13,
  },
  {
    srNo: 16,
    countryCode: 994,
    countryName: "Azerbaijan",
    maxLength: 9,
  },
  {
    srNo: 37,
    countryCode: 257,
    countryName: "Burundi",
    maxLength: 8,
  },
  {
    srNo: 22,
    countryCode: 32,
    countryName: "Belgium",
    maxLength: 9,
  },
  {
    srNo: 24,
    countryCode: 229,
    countryName: "Benin",
    maxLength: 8,
  },
  {
    srNo: 36,
    countryCode: 226,
    countryName: "Burkina Faso",
    maxLength: 8,
  },
  {
    srNo: 19,
    countryCode: 880,
    countryName: "Bangladesh",
    maxLength: 10,
  },
  {
    srNo: 35,
    countryCode: 359,
    countryName: "Bulgaria",
    maxLength: 9,
  },
  {
    srNo: 18,
    countryCode: 973,
    countryName: "Bahrain",
    maxLength: 8,
  },
  {
    srNo: 17,
    countryCode: 242,
    countryName: "Bahamas",
    maxLength: 10,
  },
  {
    srNo: 28,
    countryCode: 387,
    countryName: "Bosnia and Herzegovina",
    maxLength: 8,
  },
  {
    srNo: 184,
    countryCode: 590,
    countryName: "Saint Barthélemy",
    maxLength: 9,
  },
  {
    srNo: 21,
    countryCode: 375,
    countryName: "Belarus",
    maxLength: 9,
  },
  {
    srNo: 23,
    countryCode: 501,
    countryName: "Belize",
    maxLength: 7,
  },
  {
    srNo: 25,
    countryCode: 1441,
    countryName: "Bermuda",
    maxLength: 10,
  },
  {
    srNo: 27,
    countryCode: 591,
    countryName: "Bolivia",
    maxLength: 8,
  },
  {
    srNo: 31,
    countryCode: 55,
    countryName: "Brazil",
    maxLength: 11,
  },
  {
    srNo: 20,
    countryCode: 246,
    countryName: "Barbados",
    maxLength: 10,
  },
  {
    srNo: 34,
    countryCode: 673,
    countryName: "Brunei",
    maxLength: 7,
  },
  {
    srNo: 26,
    countryCode: 975,
    countryName: "Bhutan",
    maxLength: 8,
  },
  {
    srNo: 30,
    countryCode: 0,
    countryName: "Bouvet Island",
  },
  {
    srNo: 29,
    countryCode: 267,
    countryName: "Botswana",
    maxLength: 7,
  },
  {
    srNo: 43,
    countryCode: 236,
    countryName: "Central African Republic",
    maxLength: 8,
  },
  {
    srNo: 40,
    countryCode: 1,
    countryName: "Canada",
    maxLength: 10,
  },
  {
    srNo: 48,
    countryCode: 61,
    countryName: "Cocos Islands",
    maxLength: 9,
  },
  {
    srNo: 215,
    countryCode: 41,
    countryName: "Switzerland",
    maxLength: 9,
  },
  {
    srNo: 45,
    countryCode: 56,
    countryName: "Chile",
    maxLength: 9,
  },
  {
    srNo: 46,
    countryCode: 86,
    countryName: "China",
    maxLength: 11,
  },
  {
    srNo: 107,
    countryCode: 225,
    countryName: "Ivory Coast",
    maxLength: 8,
  },
  {
    srNo: 39,
    countryCode: 237,
    countryName: "Cameroon",
    maxLength: 9,
  },
  {
    srNo: 57,
    countryCode: 243,
    countryName: "Democratic Republic of the Congo",
    maxLength: 9,
  },
  {
    srNo: 179,
    countryCode: 242,
    countryName: "Republic of the Congo",
    maxLength: 9,
  },
  {
    srNo: 51,
    countryCode: 682,
    countryName: "Cook Islands",
    maxLength: 7,
  },
  {
    srNo: 49,
    countryCode: 57,
    countryName: "Colombia",
    maxLength: 10,
  },
  {
    srNo: 50,
    countryCode: 269,
    countryName: "Comoros",
    maxLength: 7,
  },
  {
    srNo: 41,
    countryCode: 238,
    countryName: "Cape Verde",
    maxLength: 7,
  },
  {
    srNo: 52,
    countryCode: 506,
    countryName: "Costa Rica",
    maxLength: 8,
  },
  {
    srNo: 54,
    countryCode: 53,
    countryName: "Cuba",
    maxLength: 8,
  },
  {
    srNo: 47,
    countryCode: 61,
    countryName: "Christmas Island",
    maxLength: 9,
  },
  {
    srNo: 42,
    countryCode: 345,
    countryName: "Cayman Islands",
    maxLength: 10,
  },
  {
    srNo: 55,
    countryCode: 357,
    countryName: "Cyprus",
    maxLength: 8,
  },
  {
    srNo: 56,
    countryCode: 420,
    countryName: "Czech Republic",
    maxLength: 9,
  },
  {
    srNo: 81,
    countryCode: 49,
    countryName: "Germany",
    maxLength: 11,
  },
  {
    srNo: 59,
    countryCode: 253,
    countryName: "Djibouti",
    maxLength: 8,
  },
  {
    srNo: 60,
    countryCode: 767,
    countryName: "Dominica",
    maxLength: 10,
  },
  {
    srNo: 58,
    countryCode: 45,
    countryName: "Denmark",
    maxLength: 8,
  },
  {
    srNo: 61,
    countryCode: 809,
    countryName: "Dominican Republic",
    maxLength: 10,
  },
  {
    srNo: 4,
    countryCode: 213,
    countryName: "Algeria",
    maxLength: 9,
  },
  {
    srNo: 63,
    countryCode: 593,
    countryName: "Ecuador",
    maxLength: 9,
  },
  {
    srNo: 64,
    countryCode: 20,
    countryName: "Egypt",
    maxLength: 10,
  },
  {
    srNo: 67,
    countryCode: 291,
    countryName: "Eritrea",
    maxLength: 7,
  },
  {
    srNo: 243,
    countryCode: 212,
    countryName: "Western Sahara",
    maxLength: 9,
  },
  {
    srNo: 208,
    countryCode: 34,
    countryName: "Spain",
    maxLength: 9,
  },
  {
    srNo: 68,
    countryCode: 372,
    countryName: "Estonia",
    maxLength: 8,
  },
  {
    srNo: 69,
    countryCode: 251,
    countryName: "Ethiopia",
    maxLength: 9,
  },
  {
    srNo: 73,
    countryCode: 358,
    countryName: "Finland",
    maxLength: 9,
  },
  {
    srNo: 72,
    countryCode: 679,
    countryName: "Fiji",
    maxLength: 7,
  },
  {
    srNo: 70,
    countryCode: 500,
    countryName: "Falkland Islands",
    maxLength: 5,
  },
  {
    srNo: 74,
    countryCode: 33,
    countryName: "France",
    maxLength: 9,
  },
  {
    srNo: 71,
    countryCode: 298,
    countryName: "Faroe Islands",
    maxLength: 6,
  },
  {
    srNo: 141,
    countryCode: 691,
    countryName: "Micronesia",
    maxLength: 7,
  },
  {
    srNo: 78,
    countryCode: 241,
    countryName: "Gabon",
    maxLength: 7,
  },
  {
    srNo: 233,
    countryCode: 44,
    countryName: "United Kingdom",
    maxLength: 10,
  },
  {
    srNo: 80,
    countryCode: 995,
    countryName: "Georgia",
    maxLength: 9,
  },
  {
    srNo: 90,
    countryCode: 44,
    countryName: "Guernsey",
    maxLength: 10,
  },
  {
    srNo: 82,
    countryCode: 233,
    countryName: "Ghana",
    maxLength: 9,
  },
  {
    srNo: 83,
    countryCode: 350,
    countryName: "Gibraltar",
    maxLength: 8,
  },
  {
    srNo: 91,
    countryCode: 224,
    countryName: "Guinea",
    maxLength: 8,
  },
  {
    srNo: 87,
    countryCode: 590,
    countryName: "Guadeloupe",
    maxLength: 9,
  },
  {
    srNo: 79,
    countryCode: 220,
    countryName: "Gambia",
    maxLength: 7,
  },
  {
    srNo: 92,
    countryCode: 245,
    countryName: "Guinea-Bissau",
    maxLength: 7,
  },
  {
    srNo: 66,
    countryCode: 240,
    countryName: "Equatorial Guinea",
    maxLength: 9,
  },
  {
    srNo: 84,
    countryCode: 30,
    countryName: "Greece",
    maxLength: 10,
  },
  {
    srNo: 86,
    countryCode: 473,
    countryName: "Grenada",
    maxLength: 7,
  },
  {
    srNo: 85,
    countryCode: 299,
    countryName: "Greenland",
    maxLength: 6,
  },
  {
    srNo: 89,
    countryCode: 502,
    countryName: "Guatemala",
    maxLength: 8,
  },
  {
    srNo: 75,
    countryCode: 594,
    countryName: "French Guiana",
    maxLength: 9,
  },
  {
    srNo: 88,
    countryCode: 671,
    countryName: "Guam",
    maxLength: 7,
  },
  {
    srNo: 93,
    countryCode: 592,
    countryName: "Guyana",
    maxLength: 7,
  },
  {
    srNo: 97,
    countryCode: 852,
    countryName: "Hong Kong",
    maxLength: 8,
  },
  {
    srNo: 95,
    countryCode: 0,
    countryName: "Heard Island and McDonald Islands",
    maxLength: 0,
  },
  {
    srNo: 96,
    countryCode: 504,
    countryName: "Honduras",
    maxLength: 8,
  },
  {
    srNo: 53,
    countryCode: 385,
    countryName: "Croatia",
    maxLength: 9,
  },
  {
    srNo: 94,
    countryCode: 509,
    countryName: "Haiti",
    maxLength: 8,
  },
  {
    srNo: 98,
    countryCode: 36,
    countryName: "Hungary",
    maxLength: 9,
  },
  {
    srNo: 100,
    countryCode: 62,
    countryName: "Indonesia",
    maxLength: 11,
  },
  {
    srNo: 104,
    countryCode: 44,
    countryName: "Isle of Man",
    maxLength: 10,
  },
  {
    srNo: 99,
    countryCode: 91,
    countryName: "India",
    maxLength: 10,
  },
  {
    srNo: 32,
    countryCode: 246,
    countryName: "British Indian Ocean Territory",
    maxLength: 7,
  },
  {
    srNo: 103,
    countryCode: 353,
    countryName: "Ireland",
    maxLength: 9,
  },
  {
    srNo: 101,
    countryCode: 98,
    countryName: "Iran",
    maxLength: 10,
  },
  {
    srNo: 102,
    countryCode: 964,
    countryName: "Iraq",
    maxLength: 10,
  },
  {
    srNo: 248,
    countryCode: 354,
    countryName: "Iceland",
    maxLength: 7,
  },
  {
    srNo: 105,
    countryCode: 972,
    countryName: "Israel",
    maxLength: 9,
  },
  {
    srNo: 106,
    countryCode: 39,
    countryName: "Italy",
    maxLength: 10,
  },
  {
    srNo: 108,
    countryCode: 1876,
    countryName: "Jamaica",
    maxLength: 7,
  },
  {
    srNo: 110,
    countryCode: 44,
    countryName: "Jersey",
    maxLength: 10,
  },
  {
    srNo: 111,
    countryCode: 962,
    countryName: "Jordan",
    maxLength: 9,
  },
  {
    srNo: 109,
    countryCode: 81,
    countryName: "Japan",
    maxLength: 10,
  },
  {
    srNo: 112,
    countryCode: 7,
    countryName: "Kazakhstan",
    maxLength: 10,
  },
  {
    srNo: 113,
    countryCode: 254,
    countryName: "Kenya",
    maxLength: 10,
  },
  {
    srNo: 117,
    countryCode: 996,
    countryName: "Kyrgyzstan",
    maxLength: 9,
  },
  {
    srNo: 38,
    countryCode: 855,
    countryName: "Cambodia",
    maxLength: 9,
  },
  {
    srNo: 114,
    countryCode: 686,
    countryName: "Kiribati",
    maxLength: 8,
  },
  {
    srNo: 186,
    countryCode: 869,
    countryName: "Saint Kitts and Nevis",
    maxLength: 7,
  },
  {
    srNo: 207,
    countryCode: 82,
    countryName: "South Korea",
    maxLength: 10,
  },
  {
    srNo: 116,
    countryCode: 965,
    countryName: "Kuwait",
    maxLength: 8,
  },
  {
    srNo: 118,
    countryCode: 856,
    countryName: "Laos",
    maxLength: 8,
  },
  {
    srNo: 120,
    countryCode: 961,
    countryName: "Lebanon",
    maxLength: 8,
  },
  {
    srNo: 122,
    countryCode: 231,
    countryName: "Liberia",
    maxLength: 7,
  },
  {
    srNo: 123,
    countryCode: 218,
    countryName: "Libya",
    maxLength: 9,
  },
  {
    srNo: 187,
    countryCode: 758,
    countryName: "Saint Lucia",
    maxLength: 7,
  },
  {
    srNo: 124,
    countryCode: 423,
    countryName: "Liechtenstein",
    maxLength: 7,
  },
  {
    srNo: 209,
    countryCode: 94,
    countryName: "Sri Lanka",
    maxLength: 9,
  },
  {
    srNo: 121,
    countryCode: 266,
    countryName: "Lesotho",
    maxLength: 8,
  },
  {
    srNo: 125,
    countryCode: 370,
    countryName: "Lithuania",
    maxLength: 8,
  },
  {
    srNo: 126,
    countryCode: 352,
    countryName: "Luxembourg",
    maxLength: 9,
  },
  {
    srNo: 119,
    countryCode: 371,
    countryName: "Latvia",
    maxLength: 8,
  },
  {
    srNo: 127,
    countryCode: 853,
    countryName: "Macao",
    maxLength: 8,
  },
  {
    srNo: 188,
    countryCode: 590,
    countryName: "Saint Martin",
    maxLength: 9,
  },
  {
    srNo: 147,
    countryCode: 212,
    countryName: "Morocco",
    maxLength: 9,
  },
  {
    srNo: 143,
    countryCode: 377,
    countryName: "Monaco",
    maxLength: 8,
  },
  {
    srNo: 142,
    countryCode: 373,
    countryName: "Moldova",
    maxLength: 8,
  },
  {
    srNo: 129,
    countryCode: 261,
    countryName: "Madagascar",
    maxLength: 9,
  },
  {
    srNo: 132,
    countryCode: 960,
    countryName: "Maldives",
    maxLength: 7,
  },
  {
    srNo: 140,
    countryCode: 52,
    countryName: "Mexico",
    maxLength: 10,
  },
  {
    srNo: 135,
    countryCode: 692,
    countryName: "Marshall Islands",
    maxLength: 7,
  },
  {
    srNo: 128,
    countryCode: 389,
    countryName: "Macedonia",
    maxLength: 8,
  },
  {
    srNo: 133,
    countryCode: 223,
    countryName: "Mali",
    maxLength: 8,
  },
  {
    srNo: 134,
    countryCode: 356,
    countryName: "Malta",
    maxLength: 8,
  },
  {
    srNo: 149,
    countryCode: 95,
    countryName: "Myanmar",
    maxLength: 9,
  },
  {
    srNo: 145,
    countryCode: 381,
    countryName: "Montenegro",
    maxLength: 8,
  },
  {
    srNo: 144,
    countryCode: 976,
    countryName: "Mongolia",
    maxLength: 8,
  },
  {
    srNo: 163,
    countryCode: 670,
    countryName: "Northern Mariana Islands",
    maxLength: 7,
  },
  {
    srNo: 148,
    countryCode: 258,
    countryName: "Mozambique",
    maxLength: 9,
  },
  {
    srNo: 137,
    countryCode: 222,
    countryName: "Mauritania",
    maxLength: 8,
  },
  {
    srNo: 146,
    countryCode: 664,
    countryName: "Montserrat",
    maxLength: 7,
  },
  {
    srNo: 136,
    countryCode: 596,
    countryName: "Martinique",
    maxLength: 9,
  },
  {
    srNo: 138,
    countryCode: 230,
    countryName: "Mauritius",
    maxLength: 8,
  },
  {
    srNo: 130,
    countryCode: 265,
    countryName: "Malawi",
    maxLength: 9,
  },
  {
    srNo: 131,
    countryCode: 60,
    countryName: "Malaysia",
    maxLength: 9,
  },
  {
    srNo: 139,
    countryCode: 269,
    countryName: "Mayotte",
    maxLength: 9,
  },
  {
    srNo: 150,
    countryCode: 264,
    countryName: "Namibia",
    maxLength: 9,
  },
  {
    srNo: 155,
    countryCode: 687,
    countryName: "New Caledonia",
    maxLength: 6,
  },
  {
    srNo: 158,
    countryCode: 227,
    countryName: "Niger",
    maxLength: 8,
  },
  {
    srNo: 161,
    countryCode: 672,
    countryName: "Norfolk Island",
    maxLength: 6,
  },
  {
    srNo: 159,
    countryCode: 234,
    countryName: "Nigeria",
    maxLength: 10,
  },
  {
    srNo: 157,
    countryCode: 505,
    countryName: "Nicaragua",
    maxLength: 8,
  },
  {
    srNo: 160,
    countryCode: 683,
    countryName: "Niue",
    maxLength: 4,
  },
  {
    srNo: 153,
    countryCode: 31,
    countryName: "Netherlands",
    maxLength: 9,
  },
  {
    srNo: 164,
    countryCode: 47,
    countryName: "Norway",
    maxLength: 8,
  },
  {
    srNo: 152,
    countryCode: 977,
    countryName: "Nepal",
    maxLength: 10,
  },
  {
    srNo: 151,
    countryCode: 674,
    countryName: "Nauru",
    maxLength: 7,
  },
  {
    srNo: 156,
    countryCode: 64,
    countryName: "New Zealand",
    maxLength: 9,
  },
  {
    srNo: 165,
    countryCode: 968,
    countryName: "Oman",
    maxLength: 8,
  },
  {
    srNo: 166,
    countryCode: 92,
    countryName: "Pakistan",
    maxLength: 10,
  },
  {
    srNo: 169,
    countryCode: 507,
    countryName: "Panama",
    maxLength: 8,
  },
  {
    srNo: 174,
    countryCode: 870,
    countryName: "Pitcairn",
    maxLength: 4,
  },
  {
    srNo: 172,
    countryCode: 51,
    countryName: "Peru",
    maxLength: 9,
  },
  {
    srNo: 173,
    countryCode: 63,
    countryName: "Philippines",
    maxLength: 10,
  },
  {
    srNo: 167,
    countryCode: 680,
    countryName: "Palau",
    maxLength: 7,
  },
  {
    srNo: 170,
    countryCode: 675,
    countryName: "Papua New Guinea",
    maxLength: 8,
  },
  {
    srNo: 175,
    countryCode: 48,
    countryName: "Poland",
    maxLength: 9,
  },
  { srNo: 177, countryCode: 178, countryName: "Puerto Rico", maxLength: 10 },
  { srNo: 162, countryCode: 850, countryName: "North Korea", maxLength: 10 },
  { srNo: 176, countryCode: 351, countryName: "Portugal", maxLength: 9 },
  { srNo: 171, countryCode: 595, countryName: "Paraguay", maxLength: 9 },
  {
    srNo: 168,
    countryCode: 970,
    countryName: "Palestinian Territory",
    maxLength: 9,
  },
  { srNo: 76, countryCode: 689, countryName: "French Polynesia", maxLength: 6 },
  { srNo: 178, countryCode: 974, countryName: "Qatar", maxLength: 8 },
  { srNo: 180, countryCode: 262, countryName: "Reunion", maxLength: 9 },
  { srNo: 181, countryCode: 40, countryName: "Romania", maxLength: 9 },
  { srNo: 182, countryCode: 7, countryName: "Russia", maxLength: 10 },
  { srNo: 183, countryCode: 250, countryName: "Rwanda", maxLength: 9 },
  { srNo: 194, countryCode: 966, countryName: "Saudi Arabia", maxLength: 9 },
  {
    srNo: 197,
    countryCode: 381,
    countryName: "Serbia and Montenegro",
    maxLength: 9,
  },
  { srNo: 210, countryCode: 249, countryName: "Sudan", maxLength: 9 },
  { srNo: 195, countryCode: 221, countryName: "Senegal", maxLength: 9 },
  { srNo: 200, countryCode: 65, countryName: "Singapore", maxLength: 8 },
  {
    srNo: 206,
    countryCode: 3166,
    countryName: "South Georgia and the South Sandwich Islands",
    maxLength: 6,
  },
  { srNo: 185, countryCode: 290, countryName: "Saint Helena", maxLength: 4 },
  {
    srNo: 212,
    countryCode: 47,
    countryName: "Svalbard and Jan Mayen",
    maxLength: 8,
  },
  { srNo: 203, countryCode: 677, countryName: "Solomon Islands", maxLength: 7 },
  { srNo: 199, countryCode: 232, countryName: "Sierra Leone", maxLength: 8 },
  { srNo: 65, countryCode: 503, countryName: "El Salvador", maxLength: 8 },
  { srNo: 192, countryCode: 378, countryName: "San Marino", maxLength: 9 },
  { srNo: 204, countryCode: 252, countryName: "Somalia", maxLength: 9 },
  {
    srNo: 189,
    countryCode: 508,
    countryName: "Saint Pierre and Miquelon",
    maxLength: 6,
  },
  { srNo: 196, countryCode: 381, countryName: "Serbia", maxLength: 9 },
  {
    srNo: 193,
    countryCode: 239,
    countryName: "Sao Tome and Principe",
    maxLength: 7,
  },
  { srNo: 211, countryCode: 597, countryName: "Suriname", maxLength: 7 },
  { srNo: 201, countryCode: 421, countryName: "Slovakia", maxLength: 9 },
  { srNo: 202, countryCode: 386, countryName: "Slovenia", maxLength: 8 },
  { srNo: 214, countryCode: 46, countryName: "Sweden", maxLength: 9 },
  { srNo: 213, countryCode: 268, countryName: "Swaziland", maxLength: 8 },
  { srNo: 198, countryCode: 248, countryName: "Seychelles", maxLength: 7 },
  { srNo: 216, countryCode: 963, countryName: "Syria", maxLength: 9 },
  {
    srNo: 227,
    countryCode: 649,
    countryName: "Turks and Caicos Islands",
    maxLength: 7,
  },
  { srNo: 44, countryCode: 235, countryName: "Chad", maxLength: 8 },
  { srNo: 221, countryCode: 228, countryName: "Togo", maxLength: 8 },
  { srNo: 220, countryCode: 66, countryName: "Thailand", maxLength: 9 },
  { srNo: 218, countryCode: 992, countryName: "Tajikistan", maxLength: 9 },
  { srNo: 222, countryCode: 690, countryName: "Tokelau", maxLength: 4 },
  { srNo: 226, countryCode: 993, countryName: "Turkmenistan", maxLength: 8 },
  { srNo: 62, countryCode: 670, countryName: "East Timor", maxLength: 7 },
  { srNo: 247, countryCode: 676, countryName: "Tonga", maxLength: 7 },
  {
    srNo: 223,
    countryCode: 868,
    countryName: "Trinidad and Tobago",
    maxLength: 7,
  },
  { srNo: 224, countryCode: 216, countryName: "Tunisia", maxLength: 8 },
  { srNo: 225, countryCode: 90, countryName: "Turkey", maxLength: 10 },
  { srNo: 228, countryCode: 688, countryName: "Tuvalu", maxLength: 5 },
  { srNo: 217, countryCode: 886, countryName: "Taiwan", maxLength: 9 },
  { srNo: 219, countryCode: 255, countryName: "Tanzania", maxLength: 9 },
  { srNo: 230, countryCode: 256, countryName: "Uganda", maxLength: 9 },
  { srNo: 231, countryCode: 380, countryName: "Ukraine", maxLength: 9 },
  {
    srNo: 235,
    countryCode: 699,
    countryName: "United States Minor Outlying Islands",
    maxLength: 7,
  },
  { srNo: 236, countryCode: 598, countryName: "Uruguay", maxLength: 8 },
  { srNo: 234, countryCode: 1, countryName: "United States", maxLength: 10 },
  { srNo: 237, countryCode: 998, countryName: "Uzbekistan", maxLength: 9 },
  { srNo: 239, countryCode: 379, countryName: "Vatican", maxLength: 6 },
  {
    srNo: 190,
    countryCode: 784,
    countryName: "Saint Vincent and the Grenadines",
    maxLength: 7,
  },
  { srNo: 240, countryCode: 58, countryName: "Venezuela", maxLength: 10 },
  {
    srNo: 33,
    countryCode: 284,
    countryName: "British Virgin Islands",
    maxLength: 7,
  },
  {
    srNo: 229,
    countryCode: 340,
    countryName: "U.S. Virgin Islands",
    maxLength: 7,
  },
  { srNo: 241, countryCode: 84, countryName: "Vietnam", maxLength: 10 },
  { srNo: 238, countryCode: 678, countryName: "Vanuatu", maxLength: 7 },
  {
    srNo: 242,
    countryCode: 681,
    countryName: "Wallis and Futuna",
    maxLength: 6,
  },
  { srNo: 191, countryCode: 685, countryName: "Samoa", maxLength: 7 },
  { srNo: 115, countryCode: 381, countryName: "Kosovo", maxLength: 8 },
  { srNo: 244, countryCode: 967, countryName: "Yemen", maxLength: 9 },
  { srNo: 205, countryCode: 27, countryName: "South Africa", maxLength: 9 },
  { srNo: 245, countryCode: 260, countryName: "Zambia", maxLength: 9 },
  { srNo: 246, countryCode: 263, countryName: "Zimbabwe", maxLength: 9 },
];
